---
containers:
  default:
    docker: node:latest

pipelines:
  shopify-utilities:
    steps:
      - label: 'JavsScript Utilities - Lint'
        run:
          - cd packages/javascript-utilities
          - yarn run lint