---
containers:
  default:
    docker: node:8.9.4

pipelines:
  shopify-utilities:
    steps:
      - label: 'JavsScript Utilities - Lint'
        run:
          - yarn
          - yarn workspace @shopify/javascript-utilities run lint