version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn lint
workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint