version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run: yarn
      - run: yarn workspace @shopify/javascript-utilities run build
      - run: yarn workspace @shopify/javascript-utilities run lint
      - run: yarn workspace @shopify/react-utilities run lint
workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint